export interface FilterResult {
  index: boolean
  reason?: string
}

export interface FilterOptions {
  sizeBytes?: number
  maxSizeBytes?: number
  includePatterns?: string[]
  excludePatterns?: string[]
}

const DEFAULT_MAX_SIZE = 500 * 1024

const SKIPPED_DIRS = [
  'node_modules/', 'vendor/', '.git/', 'dist/', 'build/',
  'coverage/', '__pycache__/', '.next/', '.turbo/',
]

const LOCK_FILES = ['package-lock.json', 'yarn.lock', 'Gemfile.lock', 'pnpm-lock.yaml']

const BINARY_EXTENSIONS = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.webp', '.bmp', '.tiff',
  '.woff', '.woff2', '.ttf', '.eot', '.otf',
  '.zip', '.tar', '.gz', '.rar', '.7z',
  '.pdf', '.exe', '.dll', '.so', '.dylib', '.o', '.a',
  '.pyc', '.class', '.jar',
  '.mp3', '.mp4', '.mov', '.avi', '.webm',
])

const GENERATED_HEADER_RE = /auto[- ]generated|do not edit|generated by|this file is automatically generated|automatically generated/i

function globToRegex(pattern: string): RegExp {
  const escaped = pattern
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*/g, '{{GLOBSTAR}}')
    .replace(/\*/g, '[^/]*')
    .replace(/\?/g, '[^/]')
    .replace(/\{\{GLOBSTAR\}\}/g, '.*')
  return new RegExp(`^${escaped}$`)
}

function matchesAnyPattern(filePath: string, patterns: string[]): boolean {
  return patterns.some((p) => globToRegex(p).test(filePath))
}

export function shouldIndexFile(
  filePath: string,
  content?: string,
  options?: FilterOptions,
): FilterResult {
  if (!filePath) return { index: false, reason: 'empty file path' }

  const normalized = filePath.replace(/\\/g, '/')
  const basename = normalized.split('/').pop() ?? ''
  const ext = basename.includes('.') ? '.' + basename.split('.').pop() : ''

  if (options?.includePatterns?.length && matchesAnyPattern(normalized, options.includePatterns)) {
    return { index: true }
  }

  if (options?.excludePatterns?.length && matchesAnyPattern(normalized, options.excludePatterns)) {
    return { index: false, reason: `matched exclude pattern` }
  }

  for (const dir of SKIPPED_DIRS) {
    if (normalized.includes(`/${dir}`) || normalized.startsWith(dir)) {
      return { index: false, reason: `in skipped directory: ${dir}` }
    }
  }

  if (LOCK_FILES.includes(basename) || basename.endsWith('.lock')) {
    return { index: false, reason: 'lock file' }
  }

  if (basename.endsWith('.min.js') || basename.endsWith('.min.css')) {
    return { index: false, reason: 'minified bundle' }
  }

  if (ext === '.map') {
    return { index: false, reason: 'source map' }
  }

  if (basename.includes('.generated.')) {
    return { index: false, reason: 'generated file marker' }
  }

  if (basename.endsWith('.d.ts') && normalized.includes('node_modules/')) {
    return { index: false, reason: '.d.ts in node_modules' }
  }

  if (BINARY_EXTENSIONS.has(ext)) {
    return { index: false, reason: `binary extension: ${ext}` }
  }

  const maxSize = options?.maxSizeBytes ?? DEFAULT_MAX_SIZE
  if (options?.sizeBytes != null && options.sizeBytes > maxSize) {
    return { index: false, reason: `file too large (${options.sizeBytes} > ${maxSize})` }
  }

  if (content != null) {
    const lines = content.split('\n')
    const headerLines = lines.slice(0, 10).join('\n')
    if (GENERATED_HEADER_RE.test(headerLines)) {
      return { index: false, reason: 'auto-generated header detected' }
    }

    if (lines.length < 5) {
      const totalLength = lines.reduce((sum, l) => sum + l.length, 0)
      const avgLength = totalLength / Math.max(lines.length, 1)
      if (avgLength > 500) {
        return { index: false, reason: 'minified code detected' }
      }
    }
  }

  return { index: true }
}
