// @vitest-environment node
import { describe, it, expect } from 'vitest'
import { shouldIndexFile } from './file-filter'

describe('shouldIndexFile', () => {
  describe('path-based rules', () => {
    it('skips node_modules/, vendor/, .git/, dist/, build/ directories', () => {
      expect(shouldIndexFile('node_modules/lodash/index.js').index).toBe(false)
      expect(shouldIndexFile('vendor/bundle.js').index).toBe(false)
      expect(shouldIndexFile('.git/config').index).toBe(false)
      expect(shouldIndexFile('dist/bundle.js').index).toBe(false)
      expect(shouldIndexFile('build/output.js').index).toBe(false)
      expect(shouldIndexFile('src/node_modules/test.js').index).toBe(false)
    })

    it('skips lock files', () => {
      expect(shouldIndexFile('package-lock.json').index).toBe(false)
      expect(shouldIndexFile('yarn.lock').index).toBe(false)
      expect(shouldIndexFile('Gemfile.lock').index).toBe(false)
      expect(shouldIndexFile('some.lock').index).toBe(false)
    })

    it('skips minified files', () => {
      expect(shouldIndexFile('app.min.js').index).toBe(false)
      expect(shouldIndexFile('styles.min.css').index).toBe(false)
    })

    it('skips source maps', () => {
      expect(shouldIndexFile('app.js.map').index).toBe(false)
      expect(shouldIndexFile('styles.css.map').index).toBe(false)
    })

    it('skips *.d.ts inside node_modules but NOT at project root', () => {
      expect(shouldIndexFile('node_modules/@types/node/index.d.ts').index).toBe(false)
      expect(shouldIndexFile('src/types/global.d.ts').index).toBe(true)
      expect(shouldIndexFile('custom.d.ts').index).toBe(true)
    })

    it('skips binary files by extension', () => {
      expect(shouldIndexFile('image.png').index).toBe(false)
      expect(shouldIndexFile('font.woff2').index).toBe(false)
      expect(shouldIndexFile('archive.zip').index).toBe(false)
      expect(shouldIndexFile('lib.so').index).toBe(false)
    })

    it('skips files above size threshold', () => {
      expect(shouldIndexFile('big.ts', undefined, { sizeBytes: 600000 }).index).toBe(false)
      expect(shouldIndexFile('small.ts', undefined, { sizeBytes: 100 }).index).toBe(true)
    })

    it('indexes hand-written global.d.ts at project root', () => {
      expect(shouldIndexFile('src/types/global.d.ts').index).toBe(true)
    })
  })

  describe('content-based rules', () => {
    it('detects "auto-generated" header', () => {
      const content = '// This file is auto-generated\nexport const x = 1'
      expect(shouldIndexFile('gen.ts', content).index).toBe(false)
    })

    it('detects "do not edit" header', () => {
      const content = '/* DO NOT EDIT */\nconst x = 1'
      expect(shouldIndexFile('gen.ts', content).index).toBe(false)
    })

    it('detects "generated by" header', () => {
      const content = '// Generated by protoc\nmessage Foo {}'
      expect(shouldIndexFile('gen.ts', content).index).toBe(false)
    })

    it('detects minified code', () => {
      const content = 'a'.repeat(1000)
      expect(shouldIndexFile('bundle.js', content).index).toBe(false)
    })

    it('passes normal code through content checks', () => {
      const content = 'export function hello() {\n  return "world"\n}\n'
      expect(shouldIndexFile('src/hello.ts', content).index).toBe(true)
    })
  })

  describe('user-configurable patterns', () => {
    it('include_patterns override smart detection', () => {
      const content = '// auto-generated\nexport {}'
      const result = shouldIndexFile('gen.ts', content, { includePatterns: ['gen.ts'] })
      expect(result.index).toBe(true)
    })

    it('exclude_patterns skip files that would otherwise be indexed', () => {
      const result = shouldIndexFile('src/utils/helper.ts', undefined, { excludePatterns: ['src/utils/**'] })
      expect(result.index).toBe(false)
    })

    it('glob pattern matching works for nested paths', () => {
      expect(shouldIndexFile('src/deep/nested/file.ts', undefined, { excludePatterns: ['src/**/nested/**'] }).index).toBe(false)
      expect(shouldIndexFile('src/other/file.ts', undefined, { excludePatterns: ['src/**/nested/**'] }).index).toBe(true)
    })
  })

  describe('edge cases', () => {
    it('empty file path returns false', () => {
      expect(shouldIndexFile('').index).toBe(false)
    })

    it('files without extension are not skipped', () => {
      expect(shouldIndexFile('Makefile').index).toBe(true)
      expect(shouldIndexFile('Dockerfile').index).toBe(true)
    })
  })
})
